### ISSUE TITLE
Why symlinks, and where should they link to?

### ISSUE THREAD

**Issue by thcrt** [steven-omaha/pacdef#44]
I love this project! I just had two questions:

1) Why are symlinks seemingly suggested, and
2) if I use them, where should the original group files be stored?

**Comment by steven-omaha** [comment]
Thanks for the kind words!

> Why are symlinks seemingly suggested

Because that's how I envisioned the tool being used. Have a dotfiles-repository that I check out on different hosts, from there `pacdef group import` whatever I need. But they are not a must.

> if I use them, where should the original group files be stored?

There is no one answer to this. I have a dotfiles repo, for me it's `~/dotfiles`, with a submodule `~/dotfiles/pacdef`. You can put them under `/etc/pacdef`, but if you are on Arch Linux, that does not make a lot of sense, since AUR wrappers typically refuse AUR updates if you are root, and you would need to be root to put anything there.

`pacdef group export` exports them in the current working dir. You can also add an optional path argument.

**Comment by mike-lloyd03** [comment]
Would you be interested in a PR to add a config option to silence this warning?
